// 由 tauri-specta 自动生成，请勿手动编辑。
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 窗口就绪后再显示。
 * 
 * tauri.conf.json 里 `visible: false`，等前端首帧渲染完再 show() ——
 * 否则用户会先看到一个空窗口闪一下，这是桌面应用最常见的廉价感来源。
 */
async ready() : Promise<void> {
    await TAURI_INVOKE("ready");
},
async winMinimize() : Promise<void> {
    await TAURI_INVOKE("win_minimize");
},
async winToggleMaximize() : Promise<boolean> {
    return await TAURI_INVOKE("win_toggle_maximize");
},
async winClose() : Promise<void> {
    await TAURI_INVOKE("win_close");
},
/**
 * 保存完成后真正销毁窗口。只由前端的 close guard 调用，避免再次触发
 * `onCloseRequested` 形成递归。
 */
async winForceClose() : Promise<void> {
    await TAURI_INVOKE("win_force_close");
},
async winIsMaximized() : Promise<boolean> {
    return await TAURI_INVOKE("win_is_maximized");
},
async winStartDragging() : Promise<boolean> {
    return await TAURI_INVOKE("win_start_dragging");
},
async noteList(archived: boolean) : Promise<Result<NoteSummary[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_list", { archived }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async noteGet(id: string) : Promise<Result<Note, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_get", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async noteUpsert(input: NoteInput) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_upsert", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async noteSetPinned(id: string, pinned: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_set_pinned", { id, pinned }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async noteArchive(id: string, category: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_archive", { id, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async noteRestore(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_restore", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async noteDelete(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("note_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchNotes(query: string, limit: number) : Promise<Result<SearchResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_notes", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async taskToggle(id: string) : Promise<Result<Task, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("task_toggle", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 某个周期的目标。period_start 由前端按 horizon 算好（周一 / 1 号 / 1 月 1 日），
 * domain 层会校验它确实是周期起点。没写过的周期返回空文档。
 */
async goalGet(horizon: string, periodStart: string) : Promise<Result<Goal, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("goal_get", { horizon, periodStart }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async goalSave(horizon: string, periodStart: string, contentMd: string) : Promise<Result<Goal, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("goal_save", { horizon, periodStart, contentMd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `carry_over` 只在请求「今天」时传 true：今天还没写过就延续之前最近的一天。
 */
async calendarDay(date: string, carryOver: boolean) : Promise<Result<DayDoc, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_day", { date, carryOver }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async calendarDaySave(date: string, title: string, noteMd: string) : Promise<Result<DayDoc, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_day_save", { date, title, noteMd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async calendarMarked(from: string, to: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_marked", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbStats() : Promise<Result<DbStats, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActionGroup = { title: string; tasks: Task[] }
/**
 * 跨 IPC 的错误类型。
 * 
 * 用 `#[serde(tag = "kind")]` 让前端能按类型分支处理，
 * 而不是去解析错误字符串。
 */
export type AppError = { kind: "Db"; message: string } | { kind: "NotFound"; message: string } | { kind: "Invalid"; message: string } | { kind: "BadRrule"; message: string } | { kind: "DbTooNew"; message: { found: number; supported: number } } | { kind: "Io"; message: string } | { kind: "Internal"; message: string }
export type DayDoc = { date: string; title: string; tasks: Task[]; noteMd: string; updatedAt: number; 
/**
 * 这一天还没写过、内容是从之前最近一天延续来的：那一天的日期。
 * 只有请求「今天」时才会延续；用户一编辑，就以这一天自己的身份落库。
 */
carriedFrom: string | null }
export type DbStats = { notes: number; archived: number; tasks: number; goals: number; activities: number; dbBytes: number; dbPath: string }
/**
 * 某个周期（某一周 / 某个月 / 某一年）的目标。
 * 一个周期一篇；还没写过的周期返回空文档（id 为空、updated_at 为 0），
 * 第一次保存时才落库。
 */
export type Goal = { 
/**
 * 还没落库时为空串
 */
id: string; 
/**
 * week | month | year
 */
horizon: string; title: string; 
/**
 * 周期起点：周一 / 1 号 / 1 月 1 日
 */
periodStart: string; contentMd: string; actionGroup: ActionGroup | null; createdAt: number; updatedAt: number }
export type Note = { id: string; title: string; contentMd: string; excerpt: string; icon: string; wordCount: number; isPinned: boolean; isArchived: boolean; archiveCategory: string | null; archivedAt: number | null; createdAt: number; updatedAt: number; 
/**
 * 挂在这篇笔记下的行动项分组（通过 link 表关联）
 */
actionGroup: ActionGroup | null }
/**
 * 新建 / 更新笔记的入参。
 * id 为 None 表示新建。
 */
export type NoteInput = { id: string | null; title: string; contentMd: string; icon: string | null }
/**
 * 列表用的轻量结构：不含 content_md。
 * 一个 300px 宽的列表没必要把每篇全文都传过来。
 */
export type NoteSummary = { id: string; title: string; excerpt: string; icon: string; isPinned: boolean; archiveCategory: string | null; archivedAt: number | null; createdAt: number; updatedAt: number }
export type SearchHit = { id: string; title: string; excerpt: string; icon: string; isArchived: boolean; updatedAt: number; 
/**
 * bm25 分数，越小越相关
 */
score: number }
export type SearchResult = { hits: SearchHit[]; 
/**
 * 前端拿它在原始正文上做高亮（不能用 SQLite 的 snippet，见 search.rs）
 */
tokens: string[] }
export type Task = { id: string; title: string; 
/**
 * todo | doing | done | cancelled
 */
status: string; meta: string | null; priority: number; dueDate: string | null; timeLabel: string | null; category: string | null; goalId: string | null; sortKey: string; completedAt: number | null; createdAt: number; updatedAt: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
